name: Metrics
on:
  # Agenda para rodar a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente para testar
  workflow_dispatch:
  # Roda sempre que você der push no main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # O token que você configurou no Passo 2
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções básicas
          user: TheusRibeiro  # <--- COLOQUE SEU USUARIO AQUI
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/Bahia

